- name: Restart Wireguard-quick service
  ansible.builtin.systemd:
    name: wg-quick@{{ bt_wg_interface }}.service
    state: restarted

- name: Restart qBittorrent service
  ansible.builtin.systemd:
    name: qbittorrent-nox.service
    daemon_reload: true
    state: restarted
    enabled: true
