# vim: ft=yaml.ansible
- name: "Restart Wireguard-quick service"
  ansible.builtin.systemd:
    name: "wg-quick@{{ bt_wg_interface }}.service"
    state: "restarted"

- name: "Reload systemd daemon"
  ansible.builtin.systemd:
    daemon_reload: true

- name: "Restart qBittorrent service"
  ansible.builtin.systemd:
    name: "qbittorrent-nox.service"
    state: "restarted"
