- name: Install Bind9 DNS server
  hosts: ns
  tags: dns
  gather_facts: true
  roles:
    - role: base
      become: true
    - role: dns
      become: true

- name: Install Kea DHCP server
  hosts: dhcp
  tags: dhcp
  gather_facts: true
  roles:
    - role: base
      become: true
    - role: dhcp
      become: true

- name: Install Stork agent
  hosts: stork_agent
  tags: stork_agent
  gather_facts: true
  roles:
    - role: base
      become: true
    - role: stork_agent
      become: true

- name: Install Envoy load balancer
  hosts: lb
  tags: lb
  gather_facts: true
  roles:
    - role: base
      become: true
    - role: envoy
      become: true

- name: Install bittorrent client
  hosts: bt
  tags: bt
  gather_facts: true
  roles:
    - role: base
      become: true
    - role: bt
      become: true
