# vim: ft=yaml.ansible
- name: "Base"
  hosts: "all"
  become: true
  tasks:
    - name: "Fail for wrong Linux distribution on remote machine"
      ansible.builtin.fail:
        msg: "Incorrect distribution on target machine."
      when: ansible_facts["distribution"] != "Debian"
    - name: "Install QEMU Guest Agent"
      ansible.builtin.apt:
        name:
          - "qemu-guest-agent"
        state: "present"
      notify: "Reboot"
  handlers:
    - name: "Reboot"
      ansible.builtin.reboot: {}

- name: "DNS"
  hosts: "ns"
  gather_facts: true
  roles:
    - role: dns
      become: true
