# vim: ft=yaml.ansible
- name: "Wait for cloud-init to finish"
  hosts: "all"
  tags:
    - "dns"
    - "dhcp"
    - "lb"
  tasks:
    - name: "Wait for cloud-init to finish"
      ansible.builtin.command: cloud-init status --wait
      changed_when: false

- name: "Base"
  hosts: "managed"
  tags:
    - "dns"
    - "dhcp"
    - "lb"
  become: true
  tasks:
    - name: "Fail for wrong Linux distribution on remote machine"
      ansible.builtin.fail:
        msg: "Incorrect distribution on target machine."
      when: ansible_facts["distribution"] != "Debian"

    - name: "Install base packages"
      ansible.builtin.apt:
        name:
          - "qemu-guest-agent"
          - "debian-keyring"
          - "debian-archive-keyring"
        state: "present"
        update_cache: false

    - name: "Install local stub resolver (systemd-resolved)"
      ansible.builtin.file:
        src: "/run/systemd/resolve/stub-resolv.conf"
        dest: "/etc/resolv.conf"
        state: "link"
        owner: "root"
        group: "root"
        force: true

- name: "DNS"
  hosts: "ns"
  tags: "dns"
  gather_facts: true
  roles:
    - role: "dns"
      become: true

- name: "DHCP"
  hosts: "dhcp"
  tags: "dhcp"
  gather_facts: true
  roles:
    - role: "dhcp"
      become: true

- name: "LB"
  hosts: "lb"
  tags: "lb"
  gather_facts: true
  roles:
    - role: "lb"
      become: true
