- name: Install Bind9 DNS server
  hosts: ns
  tags: dns
  gather_facts: true
  roles:
    - role: base
    - role: dns

- name: Install Kea DHCP server
  hosts: dhcp
  tags: dhcp
  gather_facts: true
  roles:
    - role: base
    - role: dhcp

- name: Install Stork agent
  hosts: stork_agent
  tags: stork_agent
  gather_facts: true
  roles:
    - role: base
    - role: stork_agent

- name: Install Envoy load balancer
  hosts: lb
  tags: lb
  gather_facts: true
  roles:
    - role: base
    - role: envoy

- name: Install bittorrent client
  hosts: bt
  tags: bt
  gather_facts: true
  roles:
    - role: base
    - role: bt
