# vim: ft=yaml.ansible
- name: "DNS"
  hosts: "ns"
  tags: "dns"
  gather_facts: true
  roles:
    - role: "base"
      become: true
    - role: "dns"
      become: true

- name: "DHCP"
  hosts: "dhcp"
  tags: "dhcp"
  gather_facts: true
  roles:
    - role: "base"
      become: true
    - role: "dhcp"
      become: true

- name: "Install stork agent"
  hosts: "stork_agent"
  tags: "stork_agent"
  gather_facts: true
  roles:
    - role: "base"
      become: true
    - role: "stork_agent"
      become: true

- name: "LB"
  hosts: "lb"
  tags: "lb"
  gather_facts: true
  roles:
    - role: "base"
      become: true
    - role: "lb"
      become: true

- name: "Bittorrent client"
  hosts: "bt"
  tags: "bt"
  gather_facts: true
  roles:
    - role: "base"
      become: true
    - role: "bt"
      become: true
