# vim: ft=yaml.ansible
- name: "Wait for cloud-init to finish"
  hosts: "all"
  tags:
    - "dns"
    - "dhcp"
    - "lb"
    - "bt"
    - "stork_agent"
  tasks:
    - name: "Wait for cloud-init to finish"
      ansible.builtin.command: cloud-init status --wait
      changed_when: false

- name: "Base"
  hosts: "all"
  tags:
    - "dns"
    - "dhcp"
    - "lb"
    - "bt"
    - "stork_agent"
  become: true
  tasks:
    - name: "Fail for wrong Linux distribution on remote machine"
      ansible.builtin.fail:
        msg: "Incorrect distribution on target machine."
      when: ansible_facts["distribution"] != "Debian"

    - name: "Install base packages"
      ansible.builtin.apt:
        name:
          - "qemu-guest-agent"
          - "debian-keyring"
          - "debian-archive-keyring"
        state: "present"
        update_cache: false

- name: "DNS"
  hosts: "ns"
  tags: "dns"
  gather_facts: true
  roles:
    - role: "dns"
      become: true

- name: "DHCP"
  hosts: "dhcp"
  tags: "dhcp"
  gather_facts: true
  roles:
    - role: "dhcp"
      become: true

- name: "Install stork agent"
  hosts: "stork_agent"
  tags: "stork_agent"
  gather_facts: true
  roles:
    - role: "stork_agent"
      become: true

- name: "LB"
  hosts: "lb"
  tags: "lb"
  gather_facts: true
  roles:
    - role: "lb"
      become: true

- name: "Bittorrent client"
  hosts: "bt"
  tags: "bt"
  gather_facts: true
  roles:
    - role: "bt"
      become: true
