managed:
  hosts:
    ns1.private.swifthomelab.net: {}
    ns2.private.swifthomelab.net: {}
    ns3.private.swifthomelab.net: {}
    ns4.private.swifthomelab.net: {}
    dhcp1.private.swifthomelab.net: {}
    # dhcp2.private.swifthomelab.net: {}
    lb1.private.swifthomelab.net: {}
    lb2.private.swifthomelab.net: {}
    bt1.fleet.private.swifthomelab.net: {}
  children:
    ns_forward:
      hosts:
        ns1.private.swifthomelab.net: {}
        ns2.private.swifthomelab.net: {}
    ns_auth_primary:
      # NOTE: hosts should be canonical DNS records, will be used to populate NS records
      hosts:
        ns3.private.swifthomelab.net: {}
      vars:
        dns_is_primary: true
    ns_auth_secondary:
      hosts:
        ns4.private.swifthomelab.net: {}
    ns_auth:
      children:
        ns_auth_primary: {}
        ns_auth_secondary: {}
      vars:
        dns_is_auth: true
    ns:
      children:
        ns_forward: {}
        ns_auth: {}
      vars:
        trusted_acl:
          - "10.0.8.0/22"
          - "10.0.3.0/24"
          - "10.0.12.0/24"
          - "10.0.1.0/24"
          - "10.1.1.2"
          - "10.1.1.3"
          - "localhost"
          - "localnets"
        dns_auth_zones:
          - zone_fqdn: "private.swifthomelab.net"
            dynamic: false
            ttl_seconds: 3600
            soa:
              serial: 53
              refresh_seconds: 7200
              retry_seconds: 1800
              expire_seconds: 86400
              minimum_seconds: 1800
            records:
              - [ "ccr2004", "A", "10.0.1.1" ]
              - [ "tlsg3210", "A", "10.0.1.2" ]
              - [ "unifi", "A", "10.0.1.3" ]
              - [ "pikvm", "A", "10.0.1.4" ]
              - [ "pve1", "A", "10.0.3.2" ]
              # - [ "pve2", "A", "10.0.3.21"]
              # - [ "pve3", "A", "10.0.3.22"]
              - [ "truenas", "A", "10.0.3.4" ]
              - [ "lb1", "A", "10.0.3.8" ]
              - [ "lb2", "A", "10.0.3.9" ]
              - [ "ns1", "A", "10.0.3.10" ]
              - [ "ns2", "A", "10.0.3.11" ]
              - [ "ns3", "A", "10.0.3.12" ]
              - [ "ns4", "A", "10.0.3.13" ]
              - [ "nsupdate", "A", "10.0.3.12" ]
              - [ "nsupdate", "A", "10.0.3.13" ]
              - [ "dhcp1", "A", "10.0.3.16" ]
              # - [ "dhcp2", "A", "10.0.3.17" ]
              - [ "lb", "A", "10.0.3.20" ]
              - [ "k8s1", "A", "10.0.12.11" ]
              - [ "k8s2", "A", "10.0.12.12" ]
              - [ "k8s3", "A", "10.0.12.13" ]
              - [ "k8s4", "A", "10.0.12.14" ]
              - [ "k8s5", "A", "10.0.12.15" ]
              - [ "k8sctrl", "A", "10.0.12.11" ]
              - [ "k8sctrl", "A", "10.0.12.12" ]
              - [ "k8sclstr", "A", "10.0.12.11" ]
              - [ "k8sclstr", "A", "10.0.12.12" ]
              - [ "k8sclstr", "A", "10.0.12.13" ]
              - [ "k8sclstr", "A", "10.0.12.14" ]
              - [ "k8sclstr", "A", "10.0.12.15" ]

          - zone_fqdn: "swifthomelab.net"
            dynamic: false
            ttl_seconds: 3600
            soa:
              serial: 36
              refresh_seconds: 7200
              retry_seconds: 1800
              expire_seconds: 86400
              minimum_seconds: 1800
            records:
              # - [ "pve", "A", "10.0.3.8" ]
              # - [ "pve", "A", "10.0.3.9" ]
              - [ "ns1.private", "A", "10.0.3.10" ]
              - [ "ns2.private", "A", "10.0.3.11" ]
              - [ "ns3.private", "A", "10.0.3.12" ]
              - [ "ns4.private", "A", "10.0.3.13" ]
              - [ "truenas", "CNAME", "truenas.private.swifthomelab.net." ]
              - [ "vault", "A", "10.0.3.8" ]
              - [ "vault", "A", "10.0.3.9" ]
              - [ "dashboard", "A", "10.0.3.8" ]
              - [ "dashboard", "A", "10.0.3.9" ]
              - [ "grafana", "A", "10.0.3.8" ]
              - [ "grafana", "A", "10.0.3.9" ]
              - [ "sync", "A", "10.0.3.8" ]
              - [ "sync", "A", "10.0.3.9" ]
              - [ "argocd", "A", "10.0.3.8" ]
              - [ "argocd", "A", "10.0.3.9" ]
              - [ "stash", "A", "10.0.3.8" ]
              - [ "stash", "A", "10.0.3.9" ]
              - [ "influxdb2", "A", "10.0.3.8" ]
              - [ "influxdb2", "A", "10.0.3.9" ]
              - [ "plex", "A", "10.0.3.8" ]
              - [ "plex", "A", "10.0.3.9" ]

          - zone_fqdn: "fleet.private.swifthomelab.net"
            dynamic: true
            dynamic_update_policy: "A DHCID"
            ttl_seconds: 3600
            soa:
              refresh_seconds: 7200
              retry_seconds: 1800
              expire_seconds: 86400
              minimum_seconds: 1800

          - zone_fqdn: "10.in-addr.arpa"
            dynamic: true
            dynamic_update_policy: "PTR DHCID"
            ttl_seconds: 3600
            soa:
              refresh_seconds: 7200
              retry_seconds: 1800
              expire_seconds: 86400
              minimum_seconds: 1800
            records:
              # canonical names only!
              - [ "1.1.0", "PTR", "ccr2004.private.swifthomelab.net." ]
              - [ "2.1.0", "PTR", "tlsg3210.private.swifthomelab.net." ]
              - [ "3.1.0", "PTR", "unifi.private.swifthomelab.net." ]
              - [ "4.1.0", "PTR", "pikvm.private.swifthomelab.net." ]
              - [ "2.3.0", "PTR", "pve1.private.swifthomelab.net." ]
              - [ "4.3.0", "PTR", "truenas.private.swifthomelab.net." ]
              - [ "8.3.0", "PTR", "lb1.private.swifthomelab.net." ]
              - [ "9.3.0", "PTR", "lb2.private.swifthomelab.net." ]
              - [ "10.3.0", "PTR", "ns1.private.swifthomelab.net." ]
              - [ "11.3.0", "PTR", "ns2.private.swifthomelab.net." ]
              - [ "12.3.0", "PTR", "ns3.private.swifthomelab.net." ]
              - [ "13.3.0", "PTR", "ns4.private.swifthomelab.net." ]
              - [ "16.3.0", "PTR", "dhcp1.private.swifthomelab.net." ]
              # - [ "17.3.0", "PTR", "dhcp2.private.swifthomelab.net." ]
              - [ "20.3.0", "PTR", "lb.private.swifthomelab.net." ]
              - [ "11.12.0", "PTR", "k8s1.private.swifthomelab.net." ]
              - [ "12.12.0", "PTR", "k8s2.private.swifthomelab.net." ]
              - [ "13.12.0", "PTR", "k8s3.private.swifthomelab.net." ]
              - [ "14.12.0", "PTR", "k8s4.private.swifthomelab.net." ]
              - [ "15.12.0", "PTR", "k8s5.private.swifthomelab.net." ]
        disable_empty_zones:
          - "10.in-addr.arpa"
    dhcp:
      hosts:
        dhcp1.private.swifthomelab.net: {}
        # dhcp2.private.swifthomelab.net: {}
      vars:
        dhcp_lease_database_lfc_interval: 3600
        dhcp_renew_timer: 900
        dhcp_rebind_timer: 1800
        dhcp_valid_lifetime: 3600
        dhcp_expired_leases_processing:
          reclaim-timer-wait-time: 5
          max-reclaim-leases: 0
          max-reclaim-time: 0
        dhcp_accept_raw_ethernet: false
        dhcp_ddns_qualifying_suffix: "fleet.private.swifthomelab.net"
        dhcp_ddns_override_client_update: true
        dhcp_dns_servers:
          - "10.0.3.10"
          - "10.0.3.11"
        dhcp_search_domain:
          - "private.swifthomelab.net"
          - "fleet.private.swifthomelab.net"
        dhcp_subnets:
          - subnet: "10.0.8.0/22"
            pools:
              - pool: "10.0.8.16 - 10.0.8.255"

              - pool: "10.0.9.0 - 10.0.9.255"

              - pool: "10.0.10.0 - 10.0.10.255"

              - pool: "10.0.11.0 - 10.0.11.254"
            option-data:
              - name: "routers"
                data: "10.0.8.1"

          - subnet: "10.0.3.0/24"
            pools:
              - pool: "10.0.3.86 - 10.0.3.254"
            option-data:
              - name: "routers"
                data: "10.0.3.1"

          - subnet: "10.0.12.0/22"
            pools:
              - pool: "10.0.12.100 - 10.0.12.255"
            option-data:
              - name: "routers"
                data: "10.0.12.1"
    lb_primary:
      hosts:
        lb1.private.swifthomelab.net: {}
      vars:
        lb_is_primary: true
    lb_secondary:
      hosts:
        lb2.private.swifthomelab.net: {}
    lb:
      children:
        lb_primary: {}
        lb_secondary: {}
      vars:
        lb_vri: 101
        lb_vip: "10.0.3.20"
        lb_envoy_config:
          static_resources:
            listeners:
              # external tcp loadbalancer for kube API-server
              - name: listener_0
                address:
                  socket_address:
                    protocol: TCP
                    address: 0.0.0.0
                    port_value: 6443
                filter_chains:
                  - filters:
                      - name: envoy.filters.network.tcp_proxy
                        typed_config:
                          "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
                          stat_prefix: destination
                          cluster: kube_apiserver

              - name: listener_1
                address:
                  socket_address:
                    protocol: TCP
                    address: 0.0.0.0
                    port_value: 443
                filter_chains:
                  - filters:
                      - name: envoy.filters.network.tcp_proxy
                        typed_config:
                          "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
                          stat_prefix: destination
                          cluster: kube_ingress

              - name: listener_2
                address:
                  socket_address:
                    protocol: TCP
                    address: 0.0.0.0
                    port_value: 80
                filter_chains:
                  - filters:
                      - name: envoy.filters.network.tcp_proxy
                        typed_config:
                          "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
                          stat_prefix: destination
                          cluster: kube_ingress_http
            clusters:
              - name: kube_apiserver
                connect_timeout: 5s
                type: STRICT_DNS
                dns_lookup_family: V4_ONLY
                lb_policy: ROUND_ROBIN
                load_assignment:
                  cluster_name: kube_apiserver
                  endpoints:
                    - lb_endpoints:
                        - endpoint:
                            address:
                              socket_address:
                                address: k8sctrl.private.swifthomelab.net
                                port_value: 6443

              - name: kube_ingress
                connect_timeout: 5s
                type: STRICT_DNS
                dns_lookup_family: V4_ONLY
                lb_policy: ROUND_ROBIN
                load_assignment:
                  cluster_name: kube_apiserver
                  endpoints:
                    - lb_endpoints:
                        - endpoint:
                            address:
                              socket_address:
                                address: k8sclstr.private.swifthomelab.net
                                port_value: 30443

              - name: kube_ingress_http
                connect_timeout: 5s
                type: STRICT_DNS
                dns_lookup_family: V4_ONLY
                lb_policy: ROUND_ROBIN
                load_assignment:
                  cluster_name: kube_apiserver
                  endpoints:
                    - lb_endpoints:
                        - endpoint:
                            address:
                              socket_address:
                                address: k8sclstr.private.swifthomelab.net
                                port_value: 30080
    bt:
      hosts:
        bt1.fleet.private.swifthomelab.net: {}
kube_control_plane:
  hosts:
    k8s1.private.swifthomelab.net: {}
    k8s2.private.swifthomelab.net: {}
kube_node:
  hosts:
    k8s1.private.swifthomelab.net: {}
    k8s2.private.swifthomelab.net: {}
    k8s3.private.swifthomelab.net: {}
    k8s4.private.swifthomelab.net: {}
    k8s5.private.swifthomelab.net: {}
etcd:
  hosts:
    k8s1.private.swifthomelab.net: {}
    k8s2.private.swifthomelab.net: {}
    k8s3.private.swifthomelab.net: {}
k8s_cluster:
  children:
    kube_control_plane: {}
    kube_node: {}
