all:
  hosts:
    ns1.private.swifthomelab.net: {}
    ns2.private.swifthomelab.net: {}
    ns3.private.swifthomelab.net: {}
    dhcp1.private.swifthomelab.net: {}
    lb1.private.swifthomelab.net: {}
    lb2.private.swifthomelab.net: {}
    bt1.private.swifthomelab.net: {}
    bt2.private.swifthomelab.net: {}
  children:
    ns_forward:
      hosts:
        ns1.private.swifthomelab.net: {}
        ns2.private.swifthomelab.net: {}
    ns_auth_primary:
      # will be used to populate NS records, hosts should be canonical DNS records
      hosts:
        ns3.private.swifthomelab.net: {}
      vars:
        dns_is_primary: true
    ns_auth_secondary:
      hosts: {}
    ns_auth:
      children:
        ns_auth_primary: {}
        ns_auth_secondary: {}
      vars:
        dns_is_auth: true
    ns:
      children:
        ns_forward: {}
        ns_auth: {}
      vars:
        trusted_acl:
          - 10.0.8.0/22
          - 10.0.3.0/24
          - 10.0.12.0/24
          - 10.0.1.0/24
          - 10.1.1.2
          - 10.1.1.3
          - localhost
          - localnets
        dns_system_nameservers:
          - 1.1.1.1
          - 1.0.0.1
        dns_local_statistics_channel_http_port: 8080
        dns_auth_zones:
          - zone_fqdn: private.swifthomelab.net
            dynamic: false
            ttl_seconds: 3600
            soa:
              serial: 61
              refresh_seconds: 7200
              retry_seconds: 1800
              expire_seconds: 86400
              minimum_seconds: 1800
            records:
              - [ ccr2004, A, 10.0.1.1 ]
              - [ tlsg3210, A, 10.0.1.2 ]
              - [ cloudkey, A, 10.0.1.3 ]
              - [ pikvm, A, 10.0.1.4 ]
              - [ pve1, A, 10.0.3.2 ]
              - [ pve2, A, 10.0.3.21 ]
              - [ pve3, A, 10.0.3.22 ]
              - [ truenas, A, 10.0.3.4 ]
              - [ lb1, A, 10.0.3.8 ]
              - [ lb2, A, 10.0.3.9 ]
              - [ ns1, A, 10.0.3.10 ]
              - [ ns2, A, 10.0.3.11 ]
              - [ ns3, A, 10.0.3.12 ]
              - [ nsupdate, A, 10.0.3.12 ]
              - [ nsupdate, A, 10.0.3.13 ]
              - [ dhcp1, A, 10.0.3.16 ]
              - [ lb, A, 10.0.3.20 ]
              - [ k8s1, A, 10.0.12.11 ]
              - [ k8s2, A, 10.0.12.12 ]
              - [ k8s3, A, 10.0.12.13 ]
              - [ etcd1, A, 10.0.12.21 ]
              - [ etcd2, A, 10.0.12.22 ]
              - [ etcd3, A, 10.0.12.23 ]
              - [ k8sctrl, A, 10.0.12.11 ]
              - [ k8sctrl, A, 10.0.12.12 ]
              - [ k8sctrl, A, 10.0.12.13 ]
              - [ k8sclstr, A, 10.0.12.11 ]
              - [ k8sclstr, A, 10.0.12.12 ]
              - [ k8sclstr, A, 10.0.12.13 ]
              - [ bt1, A, 10.0.3.24 ]
              - [ bt2, A, 10.0.3.25 ]

          - zone_fqdn: swifthomelab.net
            dynamic: false
            ttl_seconds: 3600
            soa:
              serial: 47
              refresh_seconds: 7200
              retry_seconds: 1800
              expire_seconds: 86400
              minimum_seconds: 1800
            records:
              # - [ pve, A, 10.0.3.8 ]
              # - [ pve, A, 10.0.3.9 ]
              - [ ns1.private, A, 10.0.3.10 ]
              - [ ns2.private, A, 10.0.3.11 ]
              - [ ns3.private, A, 10.0.3.12 ]
              - [ truenas, CNAME, truenas.private.swifthomelab.net. ]
              - [ vault, A, 10.0.3.8 ]
              - [ vault, A, 10.0.3.9 ]
              - [ dashboard, A, 10.0.3.8 ]
              - [ dashboard, A, 10.0.3.9 ]
              - [ grafana, A, 10.0.3.8 ]
              - [ grafana, A, 10.0.3.9 ]
              - [ sync, A, 10.0.3.8 ]
              - [ sync, A, 10.0.3.9 ]
              - [ argocd, A, 10.0.3.8 ]
              - [ argocd, A, 10.0.3.9 ]
              - [ stash, A, 10.0.3.8 ]
              - [ stash, A, 10.0.3.9 ]
              - [ influxdb2, A, 10.0.3.8 ]
              - [ influxdb2, A, 10.0.3.9 ]
              - [ plex, A, 10.0.3.8 ]
              - [ plex, A, 10.0.3.9 ]
              - [ prowlarr, A, 10.0.3.8 ]
              - [ prowlarr, A, 10.0.3.9 ]
              - [ bazarr, A, 10.0.3.8 ]
              - [ bazarr, A, 10.0.3.9 ]
              - [ sonarr, A, 10.0.3.8 ]
              - [ sonarr, A, 10.0.3.9 ]
              - [ radarr, A, 10.0.3.8 ]
              - [ radarr, A, 10.0.3.9 ]
              - [ tdarr, A, 10.0.3.8 ]
              - [ tdarr, A, 10.0.3.9 ]

          - zone_fqdn: fleet.private.swifthomelab.net
            dynamic: true
            dynamic_update_policy: A DHCID
            ttl_seconds: 3600
            soa:
              refresh_seconds: 7200
              retry_seconds: 1800
              expire_seconds: 86400
              minimum_seconds: 1800

          - zone_fqdn: 10.in-addr.arpa
            dynamic: true
            dynamic_update_policy: PTR DHCID
            ttl_seconds: 3600
            soa:
              refresh_seconds: 7200
              retry_seconds: 1800
              expire_seconds: 86400
              minimum_seconds: 1800
            records:
              # only canonical domains should be given PTR records
              # https://www.rfc-editor.org/rfc/rfc1035#section-3.5
              - [ 1.1.0, PTR, ccr2004.private.swifthomelab.net. ]
              - [ 2.1.0, PTR, tlsg3210.private.swifthomelab.net. ]
              - [ 3.1.0, PTR, cloudkey.private.swifthomelab.net. ]
              - [ 4.1.0, PTR, pikvm.private.swifthomelab.net. ]
              - [ 2.3.0, PTR, pve1.private.swifthomelab.net. ]
              - [ 4.3.0, PTR, truenas.private.swifthomelab.net. ]
              - [ 8.3.0, PTR, lb1.private.swifthomelab.net. ]
              - [ 9.3.0, PTR, lb2.private.swifthomelab.net. ]
              - [ 10.3.0, PTR, ns1.private.swifthomelab.net. ]
              - [ 11.3.0, PTR, ns2.private.swifthomelab.net. ]
              - [ 12.3.0, PTR, ns3.private.swifthomelab.net. ]
              - [ 16.3.0, PTR, dhcp1.private.swifthomelab.net. ]
              - [ 20.3.0, PTR, lb.private.swifthomelab.net. ]
              - [ 21.3.0, PTR, pve2.private.swifthomelab.net. ]
              - [ 22.3.0, PTR, pve3.private.swifthomelab.net. ]
              - [ 24.3.0, PTR, bt1.private.swifthomelab.net. ]
              - [ 25.3.0, PTR, bt2.private.swifthomelab.net. ]
              - [ 11.12.0, PTR, k8s1.private.swifthomelab.net. ]
              - [ 12.12.0, PTR, k8s2.private.swifthomelab.net. ]
              - [ 13.12.0, PTR, k8s3.private.swifthomelab.net. ]
              - [ 21.12.0, PTR, etcd1.private.swifthomelab.net. ]
              - [ 22.12.0, PTR, etcd2.private.swifthomelab.net. ]
              - [ 23.12.0, PTR, etcd3.private.swifthomelab.net. ]
        disable_empty_zones:
          - 10.in-addr.arpa
    dhcp:
      hosts:
        dhcp1.private.swifthomelab.net: {}
      vars:
        dhcp_lease_database_lfc_interval: 3600
        dhcp_renew_timer: 900
        dhcp_rebind_timer: 1800
        dhcp_valid_lifetime: 3600
        dhcp_expired_leases_processing:
          reclaim-timer-wait-time: 5
          max-reclaim-leases: 0
          max-reclaim-time: 0
        dhcp_accept_raw_ethernet: false
        dhcp_ddns_qualifying_suffix: fleet.private.swifthomelab.net
        dhcp_ddns_override_client_update: true
        dhcp_dns_servers:
          - 10.0.3.10
          - 10.0.3.11
        dhcp_search_domain:
          - private.swifthomelab.net
          - fleet.private.swifthomelab.net
        dhcp_subnets:
          - subnet: 10.0.8.0/22
            pools:
              - pool: 10.0.8.16 - 10.0.8.255

              - pool: 10.0.9.0 - 10.0.9.255

              - pool: 10.0.10.0 - 10.0.10.255

              - pool: 10.0.11.0 - 10.0.11.254
            option-data:
              - name: routers
                data: 10.0.8.1

          - subnet: 10.0.3.0/24
            pools:
              - pool: 10.0.3.86 - 10.0.3.254
            option-data:
              - name: routers
                data: 10.0.3.1

          - subnet: 10.0.12.0/22
            pools:
              - pool: 10.0.12.100 - 10.0.12.255
            option-data:
              - name: routers
                data: 10.0.12.1
    stork_agent:
      children:
        stork_agent_bind9: {}
        stork_agent_kea_dhcp: {}
      vars:
        stork_agent_port: 8002
        stork_agent_config:
          listen_prometheus_only: "true"
        stork_agent_credentials: {}
    stork_agent_bind9:
      children:
        # all dns servers
        ns: {}
      vars:
        stork_agent_is_bind9: false
        stork_agent_bind9_exporter_address: 127.0.0.1
        stork_agent_bind9_exporter_port: 9119
    stork_agent_kea_dhcp:
      children:
        # all dhcp servers
        dhcp: {}
      vars:
        stork_agent_is_kea_dhcp: true
        stork_agent_kea_exporter_address: 127.0.0.1
        stork_agent_kea_exporter_port: 9547
    lb_primary:
      hosts:
        lb1.private.swifthomelab.net: {}
      vars:
        envoy_lb_is_primary: true
    lb_secondary:
      hosts:
        lb2.private.swifthomelab.net: {}
    lb:
      children:
        lb_primary: {}
        lb_secondary: {}
      vars:
        envoy_install_keepalived: true
        envoy_lb_vri: 101
        envoy_lb_vip: 10.0.3.20
        envoy_config:
          overload_manager:
            refresh_interval: 0.25s
            resource_monitors:
              - name: envoy.resource_monitors.fixed_heap
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.resource_monitors.fixed_heap.v3.FixedHeapConfig
                  max_heap_size_bytes: 805306368  # 768 MB
            actions:
              - name: envoy.overload_actions.shrink_heap
                triggers:
                  - name: envoy.resource_monitors.fixed_heap
                    threshold:
                      value: 0.95
              - name: envoy.overload_actions.stop_accepting_requests
                triggers:
                  - name: envoy.resource_monitors.fixed_heap
                    threshold:
                      value: 0.98
          static_resources:
            listeners:
              # external TCP loadbalancer for kube API-server
              - name: listener_0
                address:
                  socket_address:
                    protocol: TCP
                    address: 0.0.0.0
                    port_value: 6443
                per_connection_buffer_limit_bytes: 32768  # 32 KiB
                filter_chains:
                  - filters:
                      - name: envoy.filters.network.tcp_proxy
                        typed_config:
                          "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
                          stat_prefix: destination
                          cluster: kube_apiserver

              # external TCP loadbalancer for Kubernetes ingress (HTTPS)
              - name: listener_1
                address:
                  socket_address:
                    protocol: TCP
                    address: 0.0.0.0
                    port_value: 443
                per_connection_buffer_limit_bytes: 32768  # 32 KiB
                filter_chains:
                  - filters:
                      - name: envoy.filters.network.tcp_proxy
                        typed_config:
                          "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
                          stat_prefix: destination
                          cluster: kube_ingress

              # external TCP loadbalancer for Kubernetes ingress (HTTP)
              - name: listener_2
                address:
                  socket_address:
                    protocol: TCP
                    address: 0.0.0.0
                    port_value: 80
                per_connection_buffer_limit_bytes: 32768  # 32 KiB
                filter_chains:
                  - filters:
                      - name: envoy.filters.network.tcp_proxy
                        typed_config:
                          "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
                          stat_prefix: destination
                          cluster: kube_ingress_http
            clusters:
              - name: kube_apiserver
                per_connection_buffer_limit_bytes: 32768  # 32 KiB
                connect_timeout: 5s
                type: STRICT_DNS
                dns_lookup_family: V4_ONLY
                lb_policy: ROUND_ROBIN
                load_assignment:
                  cluster_name: kube_apiserver
                  endpoints:
                    - lb_endpoints:
                        - endpoint:
                            address:
                              socket_address:
                                address: k8sctrl.private.swifthomelab.net
                                port_value: 6443

              - name: kube_ingress
                per_connection_buffer_limit_bytes: 32768  # 32 KiB
                connect_timeout: 5s
                type: STRICT_DNS
                dns_lookup_family: V4_ONLY
                lb_policy: ROUND_ROBIN
                load_assignment:
                  cluster_name: kube_apiserver
                  endpoints:
                    - lb_endpoints:
                        - endpoint:
                            address:
                              socket_address:
                                address: k8sclstr.private.swifthomelab.net
                                port_value: 30443

              - name: kube_ingress_http
                per_connection_buffer_limit_bytes: 32768  # 32 KiB
                connect_timeout: 5s
                type: STRICT_DNS
                dns_lookup_family: V4_ONLY
                lb_policy: ROUND_ROBIN
                load_assignment:
                  cluster_name: kube_apiserver
                  endpoints:
                    - lb_endpoints:
                        - endpoint:
                            address:
                              socket_address:
                                address: k8sclstr.private.swifthomelab.net
                                port_value: 30080
    bt_vpn:
      hosts:
        bt1.private.swifthomelab.net: {}
      vars:
        bt_wg_interface: wg0
        bt_wg_nat_keepalive: true
        bt_wg_nat_keepalive_interval: 25
        bt_wg_mtu: "1320"
        bt_wg_dns: 1.1.1.1
        bt_private_network: 10.0.3.0/24
        bt_default_interface: eth0
        bt_install_vpn: true
        bt_additional_mounts:
          - mount_point:
              path: /mnt/data
              owner: qbittorrent
              group: qbittorrent
              mode: "0700"
            fstab: truenas.private.swifthomelab.net:/mnt/artemis/data/bt1 /mnt/data nfs defaults,nofail 0 0
            systemd_mount: mnt-data.mount

          - mount_point:
              path: /mnt/qbittorrent
              owner: root
              group: root
              mode: "0755"
            fstab: /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi2-part1 /mnt/qbittorrent ext4 rw,discard,errors=remount-ro,x-systemd.growfs 0 1
            systemd_mount: mnt-qbittorrent.mount
        bt_qb_config_interface: wg0
        bt_qb_config_address: ""
        bt_qb_config_port: "15546"
        bt_qb_config_web_address: 10.0.3.24
        bt_qb_config_multiple_connections_per_ip: "false"
        bt_qb_config_autorun_enabled: "true"
        bt_qb_config_autorun_program: cp -Rl \\"%F\\" \\"/mnt/data/completed/%L\\"
        bt_qb_config_btproto: Both
    bt_no_vpn:
      hosts:
        bt2.private.swifthomelab.net: {}
      vars:
        bt_install_vpn: false
        bt_additional_mounts:
          - mount_point:
              path: /mnt/data
              owner: qbittorrent
              group: qbittorrent
              mode: "0700"
            fstab: truenas.private.swifthomelab.net:/mnt/artemis/data/bt2 /mnt/data nfs defaults,nofail 0 0
            systemd_mount: mnt-data.mount

          - mount_point:
              path: /mnt/qbittorrent
              owner: root
              group: root
              mode: "0755"
            fstab: /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi2-part1 /mnt/qbittorrent ext4 rw,discard,errors=remount-ro,x-systemd.growfs 0 1
            systemd_mount: mnt-qbittorrent.mount
        bt_qb_config_interface: eth0
        bt_qb_config_address: 10.0.3.25
        bt_qb_config_port: "52296"
        bt_qb_config_web_address: 10.0.3.25
        bt_qb_config_multiple_connections_per_ip: "true"
        bt_qb_config_autorun_enabled: "true"
        bt_qb_config_autorun_program: cp -Rl \\"%F\\" /mnt/data/completed
        bt_qb_config_btproto: Both
    bt:
      children:
        bt_vpn: {}
        bt_no_vpn: {}
      vars:
        bt_webui_port: "8443"
        bt_qb_config_default_dl_path: /mnt/data/downloads
        bt_qb_config_torrent_export_dir: /mnt/data/torrents
        bt_qb_config_content_layout: Original
  vars:
    ansible_python_interpreter: /usr/bin/python3
kube_control_plane:
  hosts:
    k8s1.private.swifthomelab.net: {}
    k8s2.private.swifthomelab.net: {}
    k8s3.private.swifthomelab.net: {}
kube_node:
  hosts:
    k8s1.private.swifthomelab.net: {}
    k8s2.private.swifthomelab.net: {}
    k8s3.private.swifthomelab.net: {}
etcd:
  hosts:
    etcd1.private.swifthomelab.net: {}
    etcd2.private.swifthomelab.net: {}
    etcd3.private.swifthomelab.net: {}
k8s_cluster:
  children:
    kube_control_plane: {}
    kube_node: {}
