ns_forward:
  hosts:
    ns1.private.swifthomelab.net:
      ansible_host: "10.0.3.10"
      ansible_user: "debian"
    ns2.private.swifthomelab.net:
      ansible_host: "10.0.3.11"
      ansible_user: "debian"
ns_auth_primary:
  hosts:
    ns3.private.swifthomelab.net:
      ansible_host: "10.0.3.12"
      ansible_user: "debian"
  vars:
    dns_is_primary: true
ns_auth_secondary:
  hosts:
    ns4.private.swifthomelab.net:
      ansible_host: "10.0.3.13"
      ansible_user: "debian"
ns_auth:
  children:
    ns_auth_primary: {}
    ns_auth_secondary: {}
  vars:
    dns_is_auth: true
ns:
  children:
    ns_forward: {}
    ns_auth: {}
  vars:
    dns_debug: false
    trusted_acl:
      - "10.0.8.0/22"
      - "10.0.3.0/24"
      - "10.0.1.0/24"
      - "10.1.1.2"
      - "10.1.1.3"
      - "localhost"
      - "localnets"
    dns_auth_zones:
      - zone_fqdn: "private.swifthomelab.net"
        dynamic: false
        ttl_seconds: 3600
        soa:
          refresh_ttl_seconds: 7200
          retry_ttl_seconds: 1800
          expire_ttl_seconds: 86400
          minimum_ttl_seconds: 1800
        records:
          - [ "ns1", "A", "10.0.3.10" ]
          - [ "ns2", "A", "10.0.3.11" ]
          - [ "ns3", "A", "10.0.3.12" ]
          - [ "ns4", "A", "10.0.3.13" ]
          - [ "pikvm", "A", "10.0.1.4" ]
          - [ "pve1", "A", "10.0.3.2" ]
          - [ "truenas", "A", "10.0.3.4" ]
          - [ "ccr2004", "A", "10.0.1.1" ]
          - [ "tlsg3210", "A", "10.0.1.2" ]
      - zone_fqdn: "fleet.private.swifthomelab.net"
        dynamic: true
        ttl_seconds: 1000
        soa:
          refresh_ttl_seconds: 7200
          retry_ttl_seconds: 1800
          expire_ttl_seconds: 86400
          minimum_ttl_seconds: 1800
lb:
  hosts:
    lb1.private.swifthomelab.net:
      ansible_host: "10.0.3.16"
      ansible_user: "debian"
    lb2.private.swifthomelab.net:
      ansible_host: "10.0.3.17"
      ansible_user: "debian"
k8s_ctrl:
  hosts:
    k8s1.private.swifthomelab.net:
      ansible_host: "10.0.3.32"
      ansible_user: "debian"
    k8s2.private.swifthomelab.net:
      ansible_host: "10.0.3.33"
      ansible_user: "debian"
    k8s3.private.swifthomelab.net:
      ansible_host: "10.0.3.34"
      ansible_user: "debian"
k8s_wrk:
  hosts:
    wrk1.private.swifthomelab.net:
      ansible_host: "10.0.3.48"
      ansible_user: "debian"
    wrk2.private.swifthomelab.net:
      ansible_host: "10.0.3.49"
      ansible_user: "debian"
k8s:
  children:
    k8s_ctrl: {}
    k8s_wrk: {}
