ns_forward:
  hosts:
    ns1.private.swifthomelab.net: {}
    ns2.private.swifthomelab.net: {}
ns_auth_primary:
  hosts:
    ns3.private.swifthomelab.net: {}
  vars:
    dns_is_primary: true
ns_auth_secondary:
  hosts:
    ns4.private.swifthomelab.net: {}
ns_auth:
  children:
    ns_auth_primary: {}
    ns_auth_secondary: {}
  vars:
    dns_is_auth: true
ns:
  children:
    ns_forward: {}
    ns_auth: {}
  vars:
    dns_debug: false
    trusted_acl:
      - "10.0.8.0/22"
      - "10.0.3.0/24"
      - "10.0.1.0/24"
      - "10.1.1.2"
      - "10.1.1.3"
      - "localhost"
      - "localnets"
    dns_auth_zones:
      - zone_fqdn: "private.swifthomelab.net"
        dynamic: false
        ttl_seconds: 3600
        soa:
          refresh_ttl_seconds: 7200
          retry_ttl_seconds: 1800
          expire_ttl_seconds: 86400
          minimum_ttl_seconds: 1800
        records:
          - [ "ns1", "A", "10.0.3.10" ]
          - [ "ns2", "A", "10.0.3.11" ]
          - [ "ns3", "A", "10.0.3.12" ]
          - [ "ns4", "A", "10.0.3.13" ]
          - [ "pikvm", "A", "10.0.1.4" ]
          - [ "pve1", "A", "10.0.3.2" ]
          - [ "truenas", "A", "10.0.3.4" ]
          - [ "ccr2004", "A", "10.0.1.1" ]
          - [ "tlsg3210", "A", "10.0.1.2" ]
      - zone_fqdn: "fleet.private.swifthomelab.net"
        dynamic: true
        ttl_seconds: 1000
        soa:
          refresh_ttl_seconds: 7200
          retry_ttl_seconds: 1800
          expire_ttl_seconds: 86400
          minimum_ttl_seconds: 1800
dhcp:
  hosts:
    dhcp1.private.swifthomelab.net: {}
    dhcp2.private.swifthomelab.net: {}
  vars:
    dhcp_lease_database_lfc_interval: 3600
    dhcp_renew_timer: 900
    dhcp_rebind_timer: 1800
    dhcp_valid_lifetime: 3600
    dhcp_expired_leases_processing:
      reclaim-timer-wait-time: 5
      max-reclaim-leases: 0
      max-reclaim-time: 0
    dhcp_accept_raw_ethernet: false
    dhcp_ddns_qualifying_suffix: "fleet.private.swifthomelab.net"
    dhcp_ddns_override_client_update: true
    dhcp_dns_servers:
      - "10.0.3.10"
      - "10.0.3.11"
    dhcp_search_domain:
      - "private.swifthomelab.net"
      - "fleet.private.swifthomelab.net"
    dhcp_subnets:
      - subnet: "10.0.8.0/22"
        pools:
          - pool: "10.0.8.16 - 10.0.8.255"

          - pool: "10.0.9.0 - 10.0.9.255"

          - pool: "10.0.10.0 - 10.0.10.255"

          - pool: "10.0.11.0 - 10.0.11.254"
        option-data:
          - name: "routers"
            data: "10.0.8.1"

      - subnet: "10.0.3.0/24"
        pools:
          - pool: "10.0.3.24 - 10.0.3.254"
        option-data:
          - name: "routers"
            data: "10.0.3.1"
lb_primary:
  hosts:
    lb1.private.swifthomelab.net: {}
  vars:
    lb_is_primary: true
lb_secondary:
  hosts:
    lb2.private.swifthomelab.net: {}
lb:
  children:
    lb_primary: {}
    lb_secondary: {}
k8s_ctrl:
  hosts:
    k8s1.private.swifthomelab.net: {}
    k8s2.private.swifthomelab.net: {}
    k8s3.private.swifthomelab.net: {}
k8s_wrk:
  hosts:
    wrk1.private.swifthomelab.net: {}
    wrk2.private.swifthomelab.net: {}
k8s:
  children:
    k8s_ctrl: {}
    k8s_wrk: {}
