- name: Restart Kea DHCP4 server
  ansible.builtin.systemd:
    name: kea-dhcp4-server.service
    state: restarted

- name: Restart Kea DHCP DDNS server
  ansible.builtin.systemd:
    name: kea-dhcp-ddns-server.service
    state: restarted

- name: Restart Kea control agent
  ansible.builtin.systemd:
    name: kea-ctrl-agent.service
    state: restarted

- name: Restart Kea DHCP6 server
  ansible.builtin.systemd:
    name: kea-dhcp6-server.service
    state: restarted
