- name: Install Envoy proxy
  ansible.builtin.include_tasks:
    file: install_envoy.yml

- name: Start and enable Envoy proxy service
  ansible.builtin.systemd:
    name: envoy.service
    state: started
    enabled: true

- name: Install keepalived
  ansible.builtin.include_tasks:
    file: install_keepalived.yml
  when: envoy_install_keepalived

- name: Start and enable keepalived service
  ansible.builtin.systemd:
    name: keepalived.service
    state: started
    enabled: true
