# vim: ft=yaml.ansible
- name: "Include secret vars"
  ansible.builtin.include_vars:
    file: "inventory/secrets.yml"

- name: "Update Kea DHCP DDNS TSIG key file"
  ansible.builtin.template:
    src: "kea-dhcp-ddns-key.conf.j2"
    dest: "/etc/kea/kea-dhcp-ddns-key.conf"
    mode: "0600"
    owner: "_kea"
    group: "root"
  notify:
    - "Restart Kea DHCP4 server"
    - "Restart Kea DHCP DDNS server"
# no_log: true

- name: "Update Kea DHCP DDNS configuration file"
  ansible.builtin.template:
    src: "kea-dhcp-ddns.conf.j2"
    dest: "/etc/kea/kea-dhcp-ddns.conf"
    mode: "0644"
    owner: "root"
    group: "root"
  notify:
    - "Restart Kea DHCP4 server"
    - "Restart Kea DHCP DDNS server"
