# vim: ft=yaml.ansible
- name: "Include debug tasks [0] "
  ansible.builtin.include_tasks:
    file: debug.yml
  when: dns_debug

- name: "Provision DNS server"
  when: not dns_debug
  block:
    - name: "Install Bind9 server and test utilities [1] "
      ansible.builtin.apt:
        name:
          - "bind9"
          - "bind9-dnsutils"
        state: "present"

    - name: "Install DNS-Over-Https stub resolver (cloudflared) [2] "
      when: not dns_is_auth
      ansible.builtin.include_tasks:
        file: cloudflared.yml

    - name: "Include alternate standby and active multi-master configs [3] "
      when: (not dns_debug) and dns_is_auth
      ansible.builtin.template:
        src: "named.conf.options.j2"
        dest: "{{ namedconf.dest }}"
        owner: "root"
        group: "bind"
        mode: "0644"
      vars:
        dns_is_primary: "{{ namedconf.active }}"
      loop:
        - active: true
          dest: "/etc/bind/named.conf.active"
        - active: false
          dest: "/etc/bind/named.conf.standby"
      loop_control:
        loop_var: "namedconf"

    - name: "Replace Bind9 zone update key [4] "
      ansible.builtin.include_tasks:
        file: "updatekey.yml"
      when: dns_is_primary

    - name: "Replace Bind9 server configuration [5] "
      ansible.builtin.include_tasks:
        file: "updatenamed.yml"

    - name: "Update zone files [6] "
      ansible.builtin.include_tasks:
        file: "updatezone.yaml"
      loop: "{{ dns_auth_zones | flatten(levels=1) }}"
      loop_control:
        loop_var: "zone"
      when: dns_is_primary

    - name: "Enable and start Bind9 service [6] "
      ansible.builtin.systemd:
        name: "named.service"
        state: "started"
        enabled: true
