# vim: ft=yaml.ansible
- name: "Replace Bind9 server configuration"
  ansible.builtin.template:
    src: "named.conf.options.j2"
    dest: "/etc/bind/named.conf.options"
    owner: "root"
    group: "bind"
    mode: "0644"
  register: config_file_mock
  check_mode: true
  when: not dns_debug

- name: "Replace Bind9 running server configuration"
  when: (not dns_debug) and config_file_mock.changed
  block:
    - name: "Freeze any dynamic zones pending server restart"
      ansible.builtin.command:
        cmd: "rndc freeze"
      changed_when: true

    - name: "Block"
      block:
        - name: "Overwrite named configuration"
          ansible.builtin.template:
            src: "named.conf.options.j2"
            dest: "/etc/bind/named.conf.options"
            owner: "root"
            group: "bind"
            mode: "0644"
            backup: true  # returns: "backup_file" attr
          register: "config_file"

        - name: "Restart Bind9 service"
          ansible.builtin.systemd:
            name: "named.service"
            state: "restarted"
      rescue:
        - name: "Print service logs"
          ansible.builtin.command:
            cmd: "journalctl -u service-name.service -b"
          changed_when: false

        - name: "Restore previous configuration"
          ansible.builtin.copy:
            remote_src: true
            src: config_file.backup_file
            dest: "/etc/bind/named.conf.options"
            owner: "root"
            group: "bind"
            mode: "0644"

        - name: "Restart Bind9 service"
          ansible.builtin.systemd:
            name: "named.service"
            state: "restarted"
      always:
        - name: "Remove temporary backup file"
          ansible.builtin.file:
            path: "{{ config_file.backup_file }}"
            state: "absent"

    - name: "Load new zones and remove any undefined zones"
      ansible.builtin.command:
        cmd: "rndc reconfig"
      changed_when: false

    - name: "Thaw any dynamic zones now that server is online"
      ansible.builtin.command:
        cmd: "rndc thaw"
      changed_when: true
