# vim: ft=yaml.ansible
- name: "Include secrets"
  ansible.builtin.include_vars:
    file: "inventory/secrets.yml"

- name: "Update dynamic Bind9 zones"
  ansible.builtin.include_tasks:
    file: "nsupdate.yml"
  when: zone.dynamic and (zone.records is defined)
  loop:
    - "{{ dns_auth_zones | ansible.builtin.combine(rndc_keys.zone_keys, rndc_keys.reverse_zone_keys) }}"
  loop_control:
    loop_var: "zone"
    label: "{{ zone.zone_fqdn }}"
