- name: Reload Envoy systemd daemon configuration
  ansible.builtin.systemd:
    name: envoy.service
    daemon_reload: true

- name: Restart Envoy service
  ansible.builtin.systemd:
    name: envoy.service
    state: restarted

- name: Restart keepalived service
  ansible.builtin.systemd:
    name: keepalived.service
    state: restarted
